Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "ubuntu/trusty64"

  config.ssh.insert_key = false

  config.vm.define :goserver do |goserver|
    goserver.vm.hostname = "goserver.dev.polaris.com"
    goserver.vm.network :private_network, ip: "192.168.2.45"
  end

  config.vm.define :goagent do |goagent|
    goagent.vm.hostname = "goagent.dev.polaris.com"
    goagent.vm.network :private_network, ip: "192.168.2.46"
  end

  config.vm.define :server1 do |server1|
    server1.vm.hostname = "server1.dev.polaris.com"
    server1.vm.network :private_network, ip: "192.168.2.50"
  end

  config.vm.define :server2 do |server2|
    server2.vm.hostname = "server2.dev.polaris.com"
    server2.vm.network :private_network, ip: "192.168.2.51"

    server2.vm.provision :ansible do |ansible|
      ansible.playbook = "site.yml"
      ansible.limit = 'all'
      ansible.sudo = true
      ansible.groups = {
        "gocd_servers"        => ["goserver"],
        "gocd_agents"         => ["goagent"],
        "factory"             => ["server1", "server2"],
        "all_groups:children" => ["gocd_servers", "gocd_agents", "server1", "server2"]
      }
    end
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--cpus', 2]
    vb.customize ['modifyvm', :id, '--memory', 2048]
  end

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = false
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

end
