---

app_web_user: web-dev
app_web_group: web-dev
app_web_home: "/opt/{{ app_web_user }}"

app_web_http_port: 8080

app_web_artifact:

app_web_java_opts: -Xmx128m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$LOGS_HOME
app_web_dw_extra_args: ""
