---

- hosts: app_web
  sudo: yes

  pre_tasks:
    - name: try to stop app
      service: name={{ app_web_user }} state=stopped
      ignore_errors: yes

    - name: purge old version
      file: path={{ app_web_home }} state=absent
      ignore_errors: yes

  roles:
    - { role: app_web }
