---

- hosts: app_recommendation
  sudo: yes

  pre_tasks:
    - name: try to stop app
      service: name={{ app_recommendation_user }} state=stopped
      ignore_errors: yes

    - name: purge old version
      file: path={{ app_recommendation_home }} state=absent
      ignore_errors: yes

  roles:
    - { role: app_recommendation }
